### ISSUE TITLE
KC login page says CIIP not CIF [3]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1080]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
-  in dev (or locally with SHOW_KC_LOGIN set to true)
- click login
- note that the text is about CIIP not CIF

Screenshots:
https://www.loom.com/share/2972d0b287eb48d99f17cc7a79cb50f2

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by LindsayMacfarlane** [comment]
@pbastia - will this bug get addressed in any of our keycloak gold migration?

**Comment by pbastia** [comment]
@LindsayMacfarlane no, the bug will still persist after the migration

**Comment by pbastia** [comment]
@LindsayMacfarlane  I got completely mistaken and I thought I was commenting on a different card. This will be addressed indeed :)

**Comment by pbastia** [comment]
Closing since this has been addressed in #823
